### ISSUE TITLE
Filter issue

### ISSUE THREAD

**Issue by gabriela99** [codeuniversity/code-resource-center#11]
Looks like the PM and STS filters are switched. 
<img width="1675" alt="screenshot 2018-11-28 at 11 02 44" src="https://user-images.githubusercontent.com/32671731/49144284-4c90b600-f2fd-11e8-8ee2-da0fcb4ab320.png">
<img width="1675" alt="screenshot 2018-11-28 at 11 02 51" src="https://user-images.githubusercontent.com/32671731/49144287-4dc1e300-f2fd-11e8-8c2f-aed684d89795.png">

**Comment by dani-santos-code** [comment]
@gabriela99 This is weird. I don't have the same issue. I believe it might be related to the new fixtures / migrations. It's not happening for me. Let's go through that tomorrow.

**Comment by gabriela99** [comment]
The issue was related to a fixture mix up. It was quickly resolved in person.
