### ISSUE TITLE
Navbar for Sign In/Register

### ISSUE THREAD

**Issue by gabriela99** [codeuniversity/code-resource-center#3]
The navbar is currently customized for when a user is already logged in. But for the sign in and register pages, this is not relevant. A separate navbar should exist for these two. Can be a separate document like base.html or directly in those two html pages. 
<img width="1664" alt="screenshot 2018-11-19 at 14 05 00" src="https://user-images.githubusercontent.com/32671731/48708896-26379000-ec04-11e8-88bd-61db4e122988.png">

**Comment by dani-santos-code** [comment]
Check the following commits: f0582617712a018717768678cbbc6f8a5ce5e687 , 15217a64fa3eb18875fff051fcd76490f672d2e0,  d7f84b947d056f5d7e1443a8415bee265c3a097b
